import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AuthAPI } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { KeyRound } from 'lucide-react'

export default function ChangePassword() {
  const navigate = useNavigate(); const { logout } = useAuth(); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const save = async (event) => { event.preventDefault(); if (newPassword !== confirm) return setError('New passwords do not match.'); setSaving(true); setError(''); try { await AuthAPI.changePassword(currentPassword, newPassword); logout(); navigate('/login', { replace: true, state: { passwordChanged: true } }) } catch (err) { setError(err?.response?.data?.message || 'Could not update password.') } finally { setSaving(false) } }
  return <div className="min-h-screen bg-asphalt flex items-center justify-center px-4"><form onSubmit={save} className="card w-full max-w-sm p-6 space-y-4"><div className="flex gap-3 items-start"><KeyRound className="w-5 h-5 text-accent mt-1" /><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-accent-deep">First sign-in security</p><h1 className="font-display text-2xl">Create your password</h1><p className="text-sm text-steel mt-1">You must change the temporary password before continuing.</p></div></div>{error && <div className="text-sm text-negative bg-negative-soft border border-negative/20 rounded px-3 py-2">{error}</div>}<label className="block"><span className="label-field">Temporary password</span><input required type="password" className="input-field" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} /></label><label className="block"><span className="label-field">New password</span><input required minLength="8" type="password" className="input-field" value={newPassword} onChange={e => setNewPassword(e.target.value)} /></label><label className="block"><span className="label-field">Confirm new password</span><input required minLength="8" type="password" className="input-field" value={confirm} onChange={e => setConfirm(e.target.value)} /></label><button disabled={saving} className="btn-accent w-full rounded py-2.5">{saving ? 'Updating…' : 'Update and sign in again'}</button></form></div>
}
