import { useCallback, useEffect, useState } from 'react'
import { FleetsAPI, UsersAPI, VehiclesAPI } from '../lib/api'
import DataTable from '../components/DataTable'
import { Badge, Field, Modal, PageHeader } from '../components/ui'
import { useAuth } from '../context/AuthContext'

const EMPTY = { name: '', clientName: '', contactName: '', contactPhone: '', fleetCodeFrom: '', fleetCodeTo: '', reservedVehicleCount: '', notes: '' }

export default function Fleets() {
  const { user } = useAuth(); const admin = ['admin', 'co_admin'].includes(user?.role); const client = user?.role === 'client'
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [form, setForm] = useState(EMPTY); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [assign, setAssign] = useState(null); const [users, setUsers] = useState([]); const [vehicles, setVehicles] = useState([]); const [assignment, setAssignment] = useState({ assignedPersonId: '', vehicleIds: [] })
  const load = useCallback(async () => { setLoading(true); try { setError(null); const r = await FleetsAPI.list(); setRows(r.data?.data || []) } catch (e) { setError(e?.response?.data?.message || 'Could not load fleets.') } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  const openCreate = () => { setEditing(null); setForm(EMPTY); setOpen(true) }
  const openEdit = row => { setEditing(row); setForm({ ...EMPTY, ...row, reservedVehicleCount: row.reservedVehicleCount || '' }); setOpen(true) }
  const save = async e => { e.preventDefault(); try { const payload = { ...form, reservedVehicleCount: Number(form.reservedVehicleCount || 0) }; if (editing) await FleetsAPI.update(editing._id, payload); else await FleetsAPI.create(payload); setOpen(false); load() } catch (err) { alert(err?.response?.data?.message || 'Could not save fleet.') } }
  const openAssign = async row => { setAssign(row); setAssignment({ assignedPersonId: row.assignedPerson?._id || '', vehicleIds: (row.vehicles || []).map(v => v._id) }); try { const [u, v] = await Promise.all([UsersAPI.list(), VehiclesAPI.list({ limit: 100 })]); setUsers(u.data?.data || []); setVehicles(v.data?.data || []) } catch { alert('Could not load assignment options.') } }
  const saveAssignment = async e => { e.preventDefault(); try { await FleetsAPI.assign(assign._id, assignment); setAssign(null); load() } catch (err) { alert(err?.response?.data?.message || 'Could not assign fleet.') } }
  const columns = [{ key: 'name', header: 'Fleet', render: r => <span className="font-medium">{r.name}</span> }, { key: 'clientName', header: 'Client' }, { key: 'fleetCodeFrom', header: 'Reserved range', render: r => r.fleetCodeFrom ? `${r.fleetCodeFrom} – ${r.fleetCodeTo || '…'}` : '—' }, { key: 'reservedVehicleCount', header: 'Requested', render: r => r.reservedVehicleCount || '—' }, { key: 'assignedPerson', header: 'Responsible person', render: r => r.assignedPerson?.name || 'Unassigned' }, { key: 'vehicles', header: 'Vehicles', render: r => r.vehicles?.map(v => v.vehicleNo).join(', ') || 'None' }, { key: 'reservationStatus', header: 'Reservation', render: r => <Badge tone={r.reservationStatus === 'approved' ? 'positive' : r.reservationStatus === 'reserved' ? 'accent' : 'steel'}>{r.reservationStatus || 'none'}</Badge> }, ...(admin ? [{ key: 'actions', header: '', render: r => <button onClick={e => { e.stopPropagation(); openAssign(r) }} className="text-xs font-semibold text-accent-deep">Assign</button> }] : [])]
  const action = admin ? <button onClick={openCreate} className="btn-accent px-3 py-2 rounded text-sm">Create fleet</button> : client ? <button onClick={openCreate} className="btn-accent px-3 py-2 rounded text-sm">Request more fleet</button> : null
  return <div><PageHeader eyebrow="Client fleet management" title="Fleets" description={client ? 'View your fleet, update its contact details, and reserve more vehicles for future work.' : 'Create client fleets, assign a responsible person and select their vehicles.'} action={action} /><DataTable columns={columns} rows={rows} loading={loading} error={error} onRowClick={admin || client ? openEdit : undefined} emptyTitle="No fleets created" emptyDescription="Create or request a fleet to begin managing vehicles." />
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Update fleet' : client ? 'Reserve more fleet' : 'Create client fleet'}><form onSubmit={save} className="space-y-4"><Field label="Fleet name"><input required className="input-field" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="Client name"><input required disabled={client && Boolean(editing)} className="input-field disabled:opacity-60" value={form.clientName} onChange={e => setForm({ ...form, clientName: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Contact"><input className="input-field" value={form.contactName} onChange={e => setForm({ ...form, contactName: e.target.value })} /></Field><Field label="Phone"><input className="input-field" value={form.contactPhone} onChange={e => setForm({ ...form, contactPhone: e.target.value })} /></Field></div><div className="grid grid-cols-3 gap-4"><Field label="Fleet code from"><input className="input-field" value={form.fleetCodeFrom} onChange={e => setForm({ ...form, fleetCodeFrom: e.target.value.toUpperCase() })} /></Field><Field label="Fleet code to"><input className="input-field" value={form.fleetCodeTo} onChange={e => setForm({ ...form, fleetCodeTo: e.target.value.toUpperCase() })} /></Field><Field label="Vehicles to reserve"><input min="0" type="number" className="input-field" value={form.reservedVehicleCount} onChange={e => setForm({ ...form, reservedVehicleCount: e.target.value })} /></Field></div><Field label="Notes"><textarea className="input-field" rows="2" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field><button className="btn-accent px-4 py-2 rounded">{editing ? 'Save changes' : client ? 'Send reservation request' : 'Create fleet'}</button></form></Modal>
    <Modal open={Boolean(assign)} onClose={() => setAssign(null)} title="Assign fleet"><form onSubmit={saveAssignment} className="space-y-4"><Field label="Responsible person"><select className="input-field" value={assignment.assignedPersonId} onChange={e => setAssignment({ ...assignment, assignedPersonId: e.target.value })}><option value="">Select person</option>{users.map(u => <option key={u._id} value={u._id}>{u.name} ({u.role})</option>)}</select></Field><Field label="Vehicles"><div className="max-h-48 overflow-y-auto border border-line rounded p-2 space-y-2">{vehicles.map(v => <label key={v._id} className="flex gap-2 text-sm"><input type="checkbox" checked={assignment.vehicleIds.includes(v._id)} onChange={e => setAssignment({ ...assignment, vehicleIds: e.target.checked ? [...assignment.vehicleIds, v._id] : assignment.vehicleIds.filter(id => id !== v._id) })} />{v.vehicleNo}</label>)}</div></Field><button className="btn-accent px-4 py-2 rounded">Save assignment</button></form></Modal>
  </div>
}
