import { useCallback, useEffect, useState } from 'react'
import { InventoryAPI } from '../lib/api'
import DataTable from '../components/DataTable'
import { Badge, Field, Modal, PageHeader, StatCard } from '../components/ui'

const EMPTY_STOCK = { name: '', category: 'tyre', unit: 'pcs', quantity: '', unitCost: '', supplier: '', paymentType: 'cash', paymentMode: 'cash', date: new Date().toISOString().slice(0, 10), notes: '' }

export default function Inventory() {
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState(null)
  const [stockOpen, setStockOpen] = useState(false)
  const [stock, setStock] = useState(EMPTY_STOCK); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { setError(null); const inventory = await InventoryAPI.list(); setItems(inventory.data?.data || []) } catch (err) { setError(err?.response?.data?.message || 'Could not load inventory.') } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  const addStock = async (event) => { event.preventDefault(); setSaving(true); try { await InventoryAPI.add({ ...stock, quantity: Number(stock.quantity), unitCost: Number(stock.unitCost) }); setStockOpen(false); setStock(EMPTY_STOCK); load() } catch (err) { alert(err?.response?.data?.message || 'Could not add stock.') } finally { setSaving(false) } }
  const totalValue = items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0)
  return <div><PageHeader eyebrow="Stock control" title="Inventory" description="Stock purchases are sent for admin approval and become available only after the accountant records payment." action={<button onClick={() => setStockOpen(true)} className="btn-accent px-3 py-2 rounded text-sm">Request stock</button>} />
    <div className="grid grid-cols-2 gap-4 mb-6"><StatCard label="Stock items" value={items.length} /><StatCard label="Inventory value" value={`₹${totalValue.toLocaleString('en-IN')}`} /></div>
    <DataTable columns={[{ key: 'name', header: 'Item', render: (r) => <span className="font-medium">{r.name}</span> }, { key: 'category', header: 'Category', render: (r) => <Badge tone="accent">{r.category}</Badge> }, { key: 'quantity', header: 'Quantity', render: (r) => `${r.quantity} ${r.unit}` }, { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'available' ? 'positive' : 'accent'}>{r.status?.replace('_', ' ') || 'available'}</Badge> }, { key: 'unitCost', header: 'Unit cost', render: (r) => `₹${Number(r.unitCost).toLocaleString('en-IN')}` }, { key: 'supplier', header: 'Supplier' }]} rows={items} loading={loading} error={error} emptyTitle="No inventory yet" emptyDescription="Request tyres, urea, diesel or custom stock for approval." />
    <Modal open={stockOpen} onClose={() => setStockOpen(false)} title="Request inventory stock"><form onSubmit={addStock} className="space-y-4"><div className="grid grid-cols-2 gap-4"><Field label="Item name"><input required className="input-field" value={stock.name} onChange={(e) => setStock({ ...stock, name: e.target.value })} /></Field><Field label="Category"><select className="input-field" value={stock.category} onChange={(e) => setStock({ ...stock, category: e.target.value })}><option value="tyre">Tyre</option><option value="urea">Urea</option><option value="diesel">Diesel</option><option value="custom">Custom</option></select></Field></div><div className="grid grid-cols-3 gap-4"><Field label="Quantity"><input required min="0.01" step="0.01" type="number" className="input-field" value={stock.quantity} onChange={(e) => setStock({ ...stock, quantity: e.target.value })} /></Field><Field label="Unit"><input required className="input-field" value={stock.unit} onChange={(e) => setStock({ ...stock, unit: e.target.value })} /></Field><Field label="Buying cost / unit"><input required min="0" step="0.01" type="number" className="input-field" value={stock.unitCost} onChange={(e) => setStock({ ...stock, unitCost: e.target.value })} /></Field></div><Field label="Supplier"><input className="input-field" value={stock.supplier} onChange={(e) => setStock({ ...stock, supplier: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Preferred payment"><select className="input-field" value={stock.paymentType} onChange={(e) => setStock({ ...stock, paymentType: e.target.value })}><option value="cash">Cash</option><option value="online">Online</option></select></Field><Field label="Request date"><input type="date" className="input-field" value={stock.date} onChange={(e) => setStock({ ...stock, date: e.target.value })} /></Field></div><p className="text-xs text-steel">This creates an approval request. The stock becomes available when an accountant marks it paid.</p><button disabled={saving} className="btn-accent px-4 py-2 rounded text-sm">{saving ? 'Sending…' : 'Send for approval'}</button></form></Modal>
  </div>
}
