const express = require("express");
const { getFleets, createFleet, updateFleet, assignFleet } = require("../controllers/fleetController");
const { protect, authorize, requirePermission } = require("../middlewares/auth");
const router = express.Router();
router.use(protect, requirePermission("fleets"));
router.get("/", getFleets);
router.post("/", createFleet);
router.put("/:id", updateFleet);
router.put("/:id/assign", authorize("admin", "co_admin"), assignFleet);
module.exports = router;
